### ISSUE TITLE
Question Conversations Between 2 users

### ISSUE THREAD

**Issue by commandantp** [AndreasHeiberg/laravel-messenger#7]
Hi!
Nice build,
Quick one I have been trying to get all the conversation between 2 users, meaning I have both their IDs. Do you have that already built in? I am trying to make that but cannot figure out how... strangely enough.
Thanks!
I tried this in the Conversation model but it will not work:
````
	public function scopeForUserWithFriend($query, $user = null, $friendUser) {
		$user_id = $user->id;
		$friendUser_id = $friendUser->id;
		return $query	->join('participants', 'conversations.id', '=', 'participants.conversation_id')
				->where('participants.user_id', $user_id)
				->where('participants.user_id', '=', $friendUser_id)
				->where('participants.deleted_at', NULL)
				->select('conversations.*'); 
	}
````

**Comment by AndreasHeiberg** [comment]
What about it doesn't work?
What does it result in?
Have you tried incrementally adding where's to see what it is that isn't behaving as you are expecting?

It looks correct to me, but I don't have a db to run it on right now.

**Comment by commandantp** [comment]
Returns an empty array even when I have a conversation share by two participants
`object(Illuminate\Database\Eloquent\Collection)#236 (1) { ["items":protected]=> array(0) { } } `

**Comment by commandantp** [comment]
By the way, is the forUser scope I add to modify the 'where(deleted_at)` to `participants.deleted_at` or I would get ambiguity constrain problem. See below the error for the query I wrote above if I keep just delete_at.

SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'deleted_at' in where clause is ambiguous (SQL: select `conversations`.* from `conversations` inner join `participants` on `conversations`.`id` = `participants`.`conversation_id` where `conversations`.`deleted_at` is null and `participants`.`user_id` = 9 and `participants`.`user_id` = 7 and `deleted_at` is null)

**Comment by commandantp** [comment]
ended up working.....

**Comment by AndreasHeiberg** [comment]
Please post you solution for people with the same issue as you in the future :) thanks

**Comment by commandantp** [comment]
added in the top message :-) almost the same thought
